### ISSUE TITLE
even shorter - 140 chars

### ISSUE THREAD

**Issue by peet** [alexlawrence/mmd#1]
``` javascript
function define(a,b,c){define[a]=require(c?b:[],c||b)}function require(a,b,c,i){for(c=[],i=0;a[i];)c[i]=define[a[i++]];return b.apply({},c)}
```

bonus(?), the a array passed into require is unmodified

**Comment by alexlawrence** [comment]
That´s simply great! Can I replace my version with yours? 
If you want to be mentioned in the license file just give me your name.
You should consider submitting this to www.140byt.es

**Comment by peet** [comment]
Sure, it's your code, I just fiddled with it.
Call me Peet.

Cheers!

**Comment by alexlawrence** [comment]
Will be using this approach in combination with a zero instead of an empty object for the factory scope (mentioned here in the comments: http://dailyjs.com/2012/06/08/physijs-scion-mmd-sorting/)

**Comment by peet** [comment]
challenge accepted!

138:

``` javascript
function define(a,b,c){define[a]=require(c?b:[],c||b)}function require(a,b,c,i){for(i^=c=[];a[i];)c[i]=define[a[i++]];return b.apply(0,c)}
```

I've been thinking about this too (134):

``` javacript
function define(a,b,c){define[a]=require(c?b:[],c||b)}function require(a,b,c,i){c=[];for(i in a)c[i]=define[a[i]];return b.apply(0,c)}
```

Although for ... in over an array is usually a bad idea (if Array.prototype has been altered), I believe in this case it is okay. Anything unexpected copied on to _c_ (likely to be _undefined_) will be ignored anyway when Function#apply is called.

**Comment by alexlawrence** [comment]
I like the version with 134 characters. I think the only thing that could happen is that arguments.length of the factory is not correct anymore.

I´ll update it to this version. If you can think of any possible problems just let me know.

**Comment by alexlawrence** [comment]
Closing this issue since the 134 characters version works fine. Thanks again!
